# Generated by Django 4.1.3 on 2022-11-15 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FullUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("SARAN", "Сарань"),
                            ("KAZ_BY", "Казыбек Би"),
                            ("MAIKEN", "Майкудук"),
                            ("JBI", "ЖБИ"),
                            ("SHAHTINSK", "Шахтинск"),
                            ("ABAY", "Абай"),
                            ("TEMIRTAU", "Темиртау"),
                        ],
                        default="KAZ_BY",
                        max_length=100,
                        verbose_name="Город",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=120, verbose_name="Должность"),
                ),
                ("date_birth", models.DateField(verbose_name="Дата рождения")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=100, verbose_name="Отчество"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
