# Generated by Django 4.1.3 on 2022-11-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_team_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team", old_name="users", new_name="users_group",
        ),
    ]
