# Generated by Django 4.1.3 on 2022-11-15 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0003_rename_users_team_users_group"),
    ]

    operations = [
        migrations.RemoveField(model_name="team", name="users_group",),
        migrations.AddField(
            model_name="team",
            name="users_group",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
